Tim0124/simple-twitter

- src/api/allAPI.js
- src/api/auth.js
- src/components/login/LoginForm.jsx
- src/components/main/MainTweets.jsx
- src/components/modal/ModalUserInfo.jsx
- src/components/register/RegisterForm.jsx
> feat: ModalUserInfo API

- package-lock.json
- package.json
- src/App.jsx
- src/Router.jsx
- src/UIcomponents/input/Input.jsx
- src/UIcomponents/layouts/Layout.jsx
- src/UIcomponents/layouts/Sidebar.jsx
- src/UIcomponents/modal/ModalPostTweet.jsx
- src/UIcomponents/modal/ModalPostTweet.module.scss
- src/api/auth.js
- src/components/admin/AdminTweetsCardsList.module.scss
- src/components/login/LoginForm.jsx
- src/components/main/MainContent.jsx
- src/components/main/MainTweets.jsx
- src/components/register/RegisterForm.jsx
修改功能：登入、註冊的功能修改
修改樣式：useInfo調整
> feat: updata component function

- package-lock.json
- src/UIcomponents/layouts/AdminSidebar.jsx
- src/UIcomponents/layouts/Layout.jsx
- src/UIcomponents/layouts/Layout.module.scss
- src/UIcomponents/layouts/SideItem.jsx
- src/UIcomponents/layouts/Sidebar.jsx
- src/UIcomponents/layouts/UserInfo.jsx
- src/api/auth.js
- src/components/admin/AdminForm.jsx
- src/components/login/LoginForm.jsx
- src/components/main/MainContent.jsx
- src/components/main/MainTweets.jsx
- src/components/modal/ModalUserInfo.jsx
- src/components/modal/ModalUserInfo.module.scss
- src/components/register/RegisterForm.jsx
- src/components/setting/SettingForm.jsx
> feat: login & register & admin & sidebar routers

- src/App.jsx
- src/Router.jsx
- src/api/authorization.js
- src/api/tweetAPI.js
- src/api/userAPI.js
- src/components/admin/AdminForm.jsx
- src/components/admin/AdminForm.module.scss
- src/components/admin/AdminTweetsItem.jsx
- src/components/admin/AdminTweetsItem.module.scss
- src/components/login/LoginForm.jsx
- src/components/register/RegisterForm.jsx
- src/context/AuthContent.jsx
- src/heplers/helpers.js
- src/pages/admin/AdminLogin.jsx
- src/pages/admin/AdminTweets.jsx
- src/pages/admin/AdminTweets.module.scss
- src/pages/admin/AdminUsers.jsx
- src/pages/admin/AdminUsers.module.scss
新增功能：後台登入API、後台推文列表和使用者清單API串接
修改樣式：串接後微調排版
> feat: add admin login and pages api function

- package-lock.json
- src/UIcomponents/buttons/Button.jsx
- src/UIcomponents/layouts/PopularUser.jsx
- src/UIcomponents/layouts/PopularUser.module.scss
- src/UIcomponents/layouts/PopularUserList.jsx
- src/UIcomponents/layouts/SideItem.jsx
- src/UIcomponents/layouts/Sidebar.jsx
- src/api/auth.js
- src/api/followingAPI.js
- src/api/likeAPI.js
- src/components/currentUser/UserLikeContent.jsx
- src/components/currentUser/UserReplyContent.jsx
- src/components/currentUser/UserTweetsContent.jsx
- src/components/currentUser/userFollow/UserFollowContent.jsx
- src/components/currentUser/userFollow/UserFollower.jsx
- src/components/login/LoginForm.jsx
- src/components/main/MainTweets.jsx
- src/components/main/MainTweetsContent.jsx
- src/components/replyList/ReplyListTweet.jsx
- src/pages/admin/AdminLogin.jsx
- src/pages/admin/AdminTweets.jsx
> feat: UserFollow API

- src/UIcomponents/layouts/PopularUser.jsx
- src/components/main/MainTweetsContent.jsx
- src/components/replyList/ReplyListTweet.jsx
> Fix: account style

- src/UIcomponents/layouts/PopularUser.jsx
- src/components/admin/AdminForm.jsx
- src/components/setting/SettingForm.jsx
> fix: format

- src/UIcomponents/buttons/Button.jsx
- src/UIcomponents/layouts/PopularUser.jsx
- src/UIcomponents/layouts/PopularUserList.jsx
- src/components/currentUser/UserLikeContent.jsx
- src/components/currentUser/UserReplyList.jsx
- src/components/currentUser/UserTweets.jsx
- src/components/currentUser/UserTweetsContent.jsx
- src/components/main/MainTweets.jsx
- src/components/main/MainTweetsContent.jsx
- src/components/replyList/ReplyListTweet.jsx
> fix: follow button & Maintweet like button"

- src/UIcomponents/layouts/PopularUserList.jsx
- src/UIcomponents/layouts/UserLayout.jsx
- src/components/main/MainTweets.jsx
- src/components/replyList/ReplyList.jsx
- src/components/replyList/ReplyListTweet.jsx
> Fix: fix error

- src/UIcomponents/modal/ModalUserInfo.jsx
> Fix: fix label for to htmlFor

- src/UIcomponents/layouts/OtherUserInfo.jsx
- src/UIcomponents/layouts/OtherUserLayout.jsx
- src/UIcomponents/layouts/PopularUserList.jsx
- src/UIcomponents/layouts/UserLayout.jsx
- src/UIcomponents/modal/ModalPostTweet.jsx
- src/UIcomponents/modal/ModalUserInfo.jsx
- src/api/auth.js
- src/api/likeAPI.js
- src/api/replyAPI.js
- src/api/tweetAPI.js
- src/api/userAPI.js
- src/components/currentUser/UserReplyList.jsx
- src/components/currentUser/UserTweets.jsx
- src/components/currentUser/userFollow/UserFollowContent.jsx
- src/components/currentUser/userFollow/UserFollowing.jsx
- src/components/main/MainTweets.jsx
- src/components/otherUser/OtherUserLike.jsx
- src/components/otherUser/OtherUserLikeContent.jsx
- src/components/otherUser/OtherUserTweetsContent.jsx
- src/components/replyList/ReplyList.jsx
- src/components/replyList/ReplyListTweet.jsx
- src/components/setting/SettingForm.jsx
> Fix: edit userInfo photo

- src/UIcomponents/layouts/OtherUserInfo.jsx
- src/UIcomponents/layouts/OtherUserInfo.module.scss
- src/UIcomponents/layouts/OtherUserLayout.jsx
- src/UIcomponents/modal/ModalUserInfo.jsx
> fix: follow button

- src/components/admin/AdminForm.jsx
- src/components/admin/AdminForm.module.scss
> fix: logout button

- src/UIcomponents/input/Input.module.scss
- src/components/admin/AdminForm.module.scss
- src/components/login/LoginForm.module.scss
- src/components/register/RegisterForm.module.scss
- src/components/setting/SettingForm.module.scss
> fix: style

- src/UIcomponents/modal/ModalUserInfo.jsx
- src/UIcomponents/modal/ModalUserInfo.module.scss
> style: editmodal style

- src/api/auth.js
- src/components/register/RegisterForm.jsx
- src/components/setting/SettingForm.jsx
> fix: error

- src/UIcomponents/modal/ModalPostTweet.jsx
- src/UIcomponents/modal/ModalPostTweet.module.scss
- src/UIcomponents/modal/ModalUserInfo.jsx
> style: modalPostTweet

- src/components/setting/SettingForm.jsx
> fix: alart

- src/UIcomponents/buttons/Button.module.scss
- src/UIcomponents/layouts/Layout.module.scss
- src/UIcomponents/modal/ModalContent.module.scss
- src/UIcomponents/modal/ModalPostTweet.jsx
- src/UIcomponents/modal/ModalPostTweet.module.scss
- src/UIcomponents/modal/ModalReplyContent.jsx
- src/UIcomponents/modal/ModalReplyContent.module.scss
- src/UIcomponents/modal/ModalReplyTweet.jsx
- src/UIcomponents/modal/ModalReplyTweet.module.scss
- src/UIcomponents/modal/ModalUserInfo.jsx
- src/UIcomponents/modal/ModalUserInfo.module.scss
- src/UIcomponents/tabs/FollowTab.jsx
- src/UIcomponents/tabs/FollowTab.module.scss
- src/UIcomponents/tabs/OtherFollowTab.jsx
- src/UIcomponents/tabs/OtherFollowTab.module.scss
- src/UIcomponents/tabs/OtherUserTab.jsx
- src/UIcomponents/tabs/OtherUserTab.module.scss
- src/UIcomponents/tabs/UserTab.jsx
- src/UIcomponents/tabs/UserTab.module.scss
- src/components/main/MainContent.module.scss
- src/components/otherUser/OtherUserLike.module.scss
- src/components/otherUser/OtherUserReplyList.module.scss
- src/components/otherUser/OtherUserTweets.module.scss
- src/components/replyList/ReplyList.jsx
- src/components/replyList/ReplyListTweet.jsx
- src/components/replyList/ReplyListTweet.module.scss
> style: update view style

- src/components/currentUser/userFollow/UserFollowContent.jsx
- src/components/currentUser/userFollow/UserFollowContent.module.scss
- src/components/currentUser/userFollow/UserFollower.jsx
- src/components/currentUser/userFollow/UserFollowing.jsx
> fix: follower button

- src/UIcomponents/layouts/OtherUserLayout.jsx
- src/UIcomponents/layouts/UserInfoHeader.jsx
- src/UIcomponents/layouts/UserInfoHeader.module.scss
- src/UIcomponents/layouts/UserLayout.jsx
- src/components/currentUser/userFollow/UserFollower.jsx
- src/components/replyList/ReplyList.jsx
- src/components/replyList/ReplyListHeader.jsx
- src/components/replyList/ReplyListTweet.jsx
> fix: change pages function

- src/components/admin/AdminTweetsCards.jsx
- src/components/admin/AdminTweetsItem.jsx
- src/pages/admin/AdminUsers.jsx
> Fix: admin user follower count

- src/UIcomponents/layouts/OtherUserInfo.jsx
- src/api/auth.js
- src/components/admin/AdminForm.jsx
- src/components/currentUser/UserLike.jsx
- src/components/currentUser/UserReplyList.jsx
- src/components/currentUser/UserTweets.jsx
- src/components/currentUser/userFollow/UserFollower.jsx
- src/components/currentUser/userFollow/UserFollowing.jsx
- src/components/main/MainTweets.jsx
- src/components/otherUser/OtherUserLike.jsx
- src/components/otherUser/OtherUserTweets.jsx
- src/components/otherUser/otherFollow/OtherUserFollower.jsx
- src/components/otherUser/otherFollow/OtherUserFollowing.jsx
- src/components/register/RegisterForm.jsx
- src/components/replyList/ReplyList.jsx
- src/components/setting/SettingForm.jsx
- src/pages/admin/AdminTweets.jsx
> Fix: error message
